#############################################################################
# Makefile for building: Prokaryotes.app/Contents/MacOS/Prokaryotes
# Generated by qmake (3.1) (Qt 5.13.2)
# Project:  ../Prokaryotes/Prokaryotes.pro
# Template: app
# Command: /Users/ozan/Development/felgo-installation/Felgo/ios/bin/qmake -o Prokaryotes.xcodeproj/project.pbxproj ../Prokaryotes/Prokaryotes.pro -spec macx-xcode CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug -after
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

MOC       = /Users/ozan/Development/felgo-installation/Felgo/ios/bin/moc
UIC       = /Users/ozan/Development/felgo-installation/Felgo/ios/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_COMPILER_SUPPORTS_SSE2 -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
INCPATH       = -I../Prokaryotes -I. -I../../../../felgo-installation/Felgo/ios/mkspecs/common/uikit -I../../../../felgo-installation/Felgo/ios/include/Felgo -I../../../../felgo-installation/Felgo/ios/include -I../../../../felgo-installation/Felgo/ios/include/QtQuick -I../../../../felgo-installation/Felgo/ios/include/QtWidgets -I../../../../felgo-installation/Felgo/ios/include/QtMultimedia -I../../../../felgo-installation/Felgo/ios/include/QtGui -I../../../../felgo-installation/Felgo/ios/include/QtQml -I../../../../felgo-installation/Felgo/ios/include/QtWebSockets -I../../../../felgo-installation/Felgo/ios/include/QtNetwork -I../../../../felgo-installation/Felgo/ios/include/QtSql -I../../../../felgo-installation/Felgo/ios/include/QtCore -I. -I../../../../felgo-installation/Felgo/ios/mkspecs/macx-ios-clang
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: qrc_resources_user.cpp
compiler_rcc_make_all: qrc_resources_user.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources_user.cpp
qrc_resources_user.cpp: ../../../../felgo-installation/Felgo/ios/mkspecs/common/felgo/resources_user.qrc \
		../../../../felgo-installation/Felgo/ios/bin/rcc \
		../../../../felgo-installation/Felgo/felgo_license.key
	/Users/ozan/Development/felgo-installation/Felgo/ios/bin/rcc -name resources_user ../../../../felgo-installation/Felgo/ios/mkspecs/common/felgo/resources_user.qrc -o qrc_resources_user.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

